language: ruby
rvm: 2.4.5
sudo: true
before_install:
- wget http://mirrors.kernel.org/ubuntu/pool/main/g/graphviz/graphviz_2.38.0-12ubuntu2_amd64.deb
- sudo apt install ./graphviz_2.38.0-12ubuntu2_amd64.deb
- wget -O ~/plantuml.jar https://repo1.maven.org/maven2/net/sourceforge/plantuml/plantuml/1.2020.1/plantuml-1.2020.1.jar
install:
- gem install bundler:2.1.4
- bundle install
script:
- asciidoctor index.adoc
- asciidoctor user_manual/index.adoc -o site/index.html -r asciidoctor-diagram
- asciidoctor user_manual/index.adoc -o site/scale18x-av-user-manual.pdf -r asciidoctor-pdf
  -r asciidoctor-diagram -b pdf -a pdf-theme=user_manual/theme.yml
- cp -r user_manual/assets/ site/
after_success:
- "./deploy.sh"
branches:
  only:
  - master
env:
  global:
  - secure: Ke2uqIPj5ns/Hu4gbMS58ojgnG/tKqkR8UGdFLiZEvj6kWexU3MMFvIGZZ3N8zKjI9K35Ub9KcSqTpMd1ZEY6dlz+Za7XQ3ueYKW54fAWH58TVxK9Yw8a1hY03lPGTzOSxBMKiC5PCdgG+sBuxMvDVZ02FpQUQ0+T/Hv9zc04BQ=
